name: Dev Workflow (Non-blocking)

on:
  push:
    branches:
      - dev
      - feature/*
      - experiment/*
      - test/*
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true  # ✅ Even if tests fail, it won’t block

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest || echo "Some tests failed, but that's okay here."

